name: Auto-All-Workflows  # 主要工作流的名称

on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:
    - cron: 0 20 * * 5  # 北京时间星期六凌晨4点，定时触发

jobs:

    LibWrt-Qihoo-360V6:
      uses: ./.github/workflows/LiBwrt-Qihoo-360V6.yml
      
    rax3000m-ImmortalWrt-A:
      uses: ./.github/workflows/RAX3000M-Imm798x-nand-A.yml

    rax3000m-ImmortalWrt-B:
      uses: ./.github/workflows/RAX3000M-Imm798x-nand-B.yml

    rax3000m-LEDE-A:
      uses: ./.github/workflows/RAX3000M-lede-nand-YM.yml

    rax3000m-LEDE-B:
      uses: ./.github/workflows/RAX3000M-lede-nand-BM.yml

    Laipeng-Qihoo-360V6:
      uses: ./.github/workflows/Laipeng-Qihoo-360V6.yml
   
    RAX3000M-ImmortalWrt:
      uses: ./.github/workflows/RAX3000M-ImmortalWrt.yml

    All-Clean:
      uses: ./.github/workflows/All-Clean.yml
